changelog:
    exclude:
        labels:
            - ignore-for-release
        authors:
            - dependabot
    categories:
        - title: 🚀 Nouveautés
          labels:
              - enhancement
              - feature
        - title: 🐛 Corrections de bugs
          labels:
              - bug
        - title: 🧹 Refactorisation
          labels:
              - refactor
        - title: 📦 Mises à jour de dépendances
          labels:
              - dependencies
        - title: 🔧 Autres changements
          labels:
              - "*"
